"""empty message

Revision ID: 00b5524c4b6b
Revises: 
Create Date: 2019-05-29 05:10:03.961219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b5524c4b6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('users', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
