"""empty message

Revision ID: 35261f4f9597
Revises: 8c098ad8721c
Create Date: 2019-05-31 15:40:58.684323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35261f4f9597'
down_revision = '8c098ad8721c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticated')
    # ### end Alembic commands ###
