"""empty message

Revision ID: 5cf6c37cf42a
Revises: 72a7aec0f22e
Create Date: 2019-05-29 06:05:05.331987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf6c37cf42a'
down_revision = '72a7aec0f22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('entries', 'phone_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('phone_num', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('entries', 'name')
    # ### end Alembic commands ###
