"""empty message

Revision ID: 69830c7ff527
Revises: dbb60b57a605
Create Date: 2019-06-23 19:16:00.377372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69830c7ff527'
down_revision = 'dbb60b57a605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###
