"""empty message

Revision ID: 8c098ad8721c
Revises: 
Create Date: 2019-05-29 06:17:05.402930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c098ad8721c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('entries', 'phone_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('phone_num', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('entries', 'name')
    # ### end Alembic commands ###
