"""empty message

Revision ID: dbb60b57a605
Revises: 3f68faa416b1
Create Date: 2019-05-31 19:19:35.229296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb60b57a605'
down_revision = '3f68faa416b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_authenticated', sa.Boolean(), nullable=True))
    op.drop_column('users', 'authenticated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_authenticated')
    op.drop_column('users', 'is_anonymous')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
